import React, { useEffect } from "react";
import { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import { Video } from "../types";
import VideoCard from "../components/VideoCard";
import NoResults from "../components/NoResults";
import { BASE_URL } from "../utils";
import useAuthStore from "../store/authStore";

interface IProps {
  videos: Video[];
}

const Home = ({ videos }: IProps) => {
  const { userProfile } = useAuthStore();

  // useEffect(() => {
  //   if (window.location.pathname === "/" && !window.location.search) {
  //     Notification.requestPermission().then((perm) => {
  //       if (perm === "granted") {
  //         const notification = new Notification("", {
  //           body: "Welcome to this wonderful social media app!!!",
  //           icon: "https://www.leagueteamupdates.com/wp-content/uploads/2017/10/Dream-League-Soccer-India-Team-Logo.jpg",
  //           image:
  //             "https://miro.medium.com/max/800/1*05xJ_KUbt6aPdDqI33UnCQ.jpeg",
  //           data: {
  //             hello: "world",
  //           },
  //         });
  //       }
  //     });
  //   }
  // }, []);

  return (
    <div className="flex flex-col gap-10 videos h-full">
      <Head>
        <title>Tiktik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {userProfile ? (
        videos.length ? (
          videos.map((video: Video) => (
            <VideoCard post={video} key={video._id} />
          ))
        ) : (
          <NoResults text={"No Videos"} />
        )
      ) : (
        <h1 className="text-xl ml-0">Login to view & upload videos</h1>
      )}
    </div>
  );
};

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  let response = null;
  if (topic) {
    response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  } else {
    response = await axios.get(`${BASE_URL}/api/post`);
  }

  return {
    props: {
      videos: response.data,
    },
  };
};
export default Home;
